### ISSUE TITLE
Add the Clevo P751DM2-G laptop to this list

### ISSUE THREAD

**Issue by Brainiarc7** [lnxnvgs-laptop-list/GSync-Laptops#1]
Also see:

1. https://gist.github.com/Brainiarc7/6a1652d4da6a30ae3c525c7d063d1277

2. https://gist.github.com/Brainiarc7/ba998de74aec480c25dd16f064a6d413

**Comment by cybik** [comment]
Boom! https://github.com/lnxnvgs-laptop-list/GSync-Laptops/commit/8d5a55bc313b275a19ed9ab9641188fd8547f394

**Comment by cybik** [comment]
Can this be marked as confirmed (first-hand experience)?

Just asking for clarity and stuff.

**Comment by Brainiarc7** [comment]
Yes, confirmed.
I own the laptop, a variant branded as the Origin Eon 15-X (from 2017).

**Comment by Brainiarc7** [comment]
Confirmed first hand, I own the laptop.

**Comment by cybik** [comment]
https://github.com/lnxnvgs-laptop-list/GSync-Laptops/commit/1c3c9789b34f3a9a77d6114fb8862cf9848c15cf

Done :D
